/* views2.jsx — Carbon Accounting, Compliance, Data Pipeline, Field companion */
const D2 = window.DMRV;
const fmt2 = D2.fmt;
const MM = window.M;

/* ---- Methodology catalog (codified logic per standard) ---- */
const METHODS = [
  { id: 'VM0048', short: 'VM0048', name: 'Reducing Emissions from Deforestation (REDD+)', registry: 'Verra VCS', tone: 'brand', status: 'Active · Phase 1' },
  { id: 'VM0047', short: 'VM0047', name: 'Afforestation, Reforestation & Revegetation (ARR)', registry: 'Verra VCS', tone: 'teal', status: 'Codified · Phase 1' },
  { id: 'VM0042', short: 'VM0042', name: 'Improved Agricultural Land Management', registry: 'Verra VCS', tone: 'gold', status: 'Phase 2' },
  { id: 'VM0007', short: 'VM0007', name: 'REDD+ Methodology Framework', registry: 'Verra VCS', tone: 'info', status: 'Phase 2' },
  { id: 'VM0033', short: 'VM0033', name: 'Tidal Wetland & Seagrass Restoration', registry: 'Verra VCS', tone: 'teal', status: 'Phase 2' },
  { id: 'VM0032', short: 'VM0032', name: 'Sustainable Grasslands (fire & grazing)', registry: 'Verra VCS', tone: 'gold', status: 'Backlog' },
  { id: 'ART-TREES', short: 'ART TREES', name: 'Jurisdictional & Nested REDD+', registry: 'ART Registry', tone: 'info', status: 'Phase 3' },
  { id: 'GS4GG', short: 'Gold Standard', name: 'GS4GG · Land Use & Forests A/R', registry: 'Gold Standard', tone: 'ai', status: 'Phase 3' },
];
function methodSteps(id, p) {
  const stk = MM(p.carbonStock) + ' tCO₂e';
  const table = {
    'VM0048': [
      ['Baseline scenario', 'Historical deforestation rate from SI Forest Cover Benchmark Map (VT0007). Refreshed dynamically each cycle.', p.baselineRate ? p.baselineRate + '%/yr loss' : 'jurisdictional rate'],
      ['Project carbon stock', 'Annual stocks across 4 pools from validated Measurement Engine outputs.', stk],
      ['Leakage', 'Activity-shifting via HabitatMapper™ leakage-belt land cover time series.', (p.leakagePct || 0) + '%'],
      ['Net additionality', 'Dynamic baseline − project − leakage, anchored on live control plots.', p.additionality],
      ['Credit forecast', 'Lower bound of 90% CI used for issuance (VM0048 §5.3).', p.creditForecast ? MM(p.creditForecast) + '/yr' : 'pending'],
    ],
    'VM0047': [
      ['Baseline', 'Pre-project carbon held constant on degraded land (zero / low baseline).', 'static baseline'],
      ['Project removals', 'AGB + BGB + SOC accumulation from planting; allometric + EO time series.', stk],
      ['Leakage', 'Activity-shifting & ecological leakage deduction.', (p.leakagePct || 4) + '%'],
      ['Additionality', 'Performance benchmark + investment / barrier analysis.', 'benchmark + barrier'],
      ['Net removals', 'GHG removals minus buffer pool; conservative lower CI applied.', 'buffer 15–20%'],
    ],
    'VM0042': [
      ['Baseline', 'Common-practice management; SOC trajectory modelled (DayCent / RothC) or measured.', 'modelled SOC'],
      ['Project SOC', 'Soil cores + remote covariates (iSDAsoil); SOC stock change to 30 cm.', 'ΔSOC tC/ha'],
      ['N₂O & CH₄', 'Fertiliser, residue & livestock emission factors (IPCC Tier 1–2).', 'emission factors'],
      ['Leakage', 'Production-displacement (yield) leakage assessment.', 'yield-based'],
      ['Net reductions', 'SOC gain + emission reductions, conservative deduction applied.', 'net tCO₂e/yr'],
    ],
    'VM0007': [
      ['Reference region', 'Historical deforestation & degradation rate across the reference region.', 'historical rate'],
      ['Baseline projection', 'Activity data × emission factors per carbon pool.', 'AD × EF'],
      ['Project monitoring', 'Forest-cover change detected via EO (Sentinel-2 + SAR).', 'EO change'],
      ['Leakage belt', 'Displacement monitoring in the defined leakage belt.', '10 km belt'],
      ['Net ERR', 'Baseline − project − leakage emission reductions & removals.', 'net ERR'],
    ],
    'VM0033': [
      ['Baseline', 'Without-project wetland loss and soil organic carbon oxidation.', 'SOC oxidation'],
      ['Project stock', 'Mangrove AGB / BGB + sediment SOC accumulation.', stk],
      ['Allochthonous adj.', 'Deduction for carbon not generated by the project.', 'autochthonous %'],
      ['Leakage', 'Displacement of degradation pressure.', 'displacement'],
      ['Net removals', 'Conservative removals including soil & biomass pools.', 'incl. soil pool'],
    ],
    'VM0032': [
      ['Baseline', 'Continued degradation under the existing fire & grazing regime.', 'degradation'],
      ['Project stock', 'AGB + SOC response to adjusted fire & grazing management.', stk],
      ['Non-CO₂', 'Fire-related CH₄ & N₂O emissions accounting.', 'fire CH₄/N₂O'],
      ['Leakage', 'Grazing-displacement assessment.', 'grazing shift'],
      ['Net reductions', 'Net SOC + biomass gain, conservative deduction.', 'net tCO₂e'],
    ],
    'ART-TREES': [
      ['Crediting baseline', 'Adjusted national / jurisdictional Forest Reference Emission Level.', 'adjusted FREL'],
      ['Activity data', 'Wall-to-wall forest-cover change from EO.', 'EO wall-to-wall'],
      ['Emission factors', 'Biomass density per forest stratum.', 'per-stratum EF'],
      ['Uncertainty', 'TREES uncertainty deduction applied to gross estimate.', 'TREES discount'],
      ['Net removals', 'Gross vs FREL with HFLD provisions.', 'vs FREL'],
    ],
    'GS4GG': [
      ['Baseline', 'Pre-project land-use carbon stock & trajectory.', 'land-use baseline'],
      ['Project removals', 'Tree growth via species-specific allometrics + EO.', stk],
      ['Leakage', 'Activity-shifting leakage deduction.', 'activity-shift'],
      ['Safeguards & SDGs', 'Co-benefit monitoring against Gold Standard SDG requirements.', '≥3 SDGs'],
      ['Net removals', 'Conservative removals with buffer contribution.', 'buffered'],
    ],
  };
  return (table[id] || table['VM0048']).map((s, i) => ({ n: i + 1, t: s[0], d: s[1], v: s[2] }));
}
function MethodPicker({ value, onChange }) {
  const [open, setOpen] = React.useState(false);
  const cur = METHODS.find(m => m.id === value) || METHODS[0];
  return <div style={{ position: 'relative' }}>
    <button className="vc-btn-ghost" style={{ padding: '6px 10px' }} onClick={() => setOpen(o => !o)}>
      <Icon name="list" size={13} c="var(--brand)" />
      <span style={{ fontWeight: 600 }}>{cur.short}</span>
      <Icon name="chevD" size={12} />
    </button>
    {open && <>
      <div style={{ position: 'fixed', inset: 0, zIndex: 40 }} onClick={() => setOpen(false)} />
      <div className="panel" style={{ position: 'absolute', top: '112%', right: 0, width: 320, zIndex: 41, padding: 6, maxHeight: 380, overflow: 'auto' }}>
        <div className="lbl" style={{ padding: '6px 8px 4px' }}>Methodology</div>
        {METHODS.map(m => <div key={m.id} className="nav-item" style={{ borderRadius: 7, alignItems: 'flex-start' }} onClick={() => { onChange(m.id); setOpen(false); }}>
          <span style={{ marginTop: 2 }}><Icon name="calc" size={14} c={m.id === value ? 'var(--brand)' : 'var(--text-3)'} /></span>
          <div style={{ flex: 1, minWidth: 0 }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 7 }}>
              <span style={{ fontSize: 12.5, fontWeight: 700 }}>{m.short}</span>
              <Badge tone={m.tone}>{m.status}</Badge>
            </div>
            <div style={{ fontSize: 11, color: 'var(--text-3)', marginTop: 2, whiteSpace: 'normal', lineHeight: 1.35 }}>{m.name} · {m.registry}</div>
          </div>
          {m.id === value && <Icon name="check" size={14} c="var(--brand)" />}
        </div>)}
      </div>
    </>}
  </div>;
}

/* ===================== CARBON ACCOUNTING ENGINE ===================== */
function AccountingView({ project, t }) {
  const p = project;
  const [method, setMethod] = React.useState('VM0048');
  const curMethod = METHODS.find(m => m.id === method) || METHODS[0];
  const startYr = parseInt(p.creditPeriod) || 2024;
  // forward forecast rows
  const rows = React.useMemo(() => {
    const base = p.creditForecast || (p.carbonStock * 0.045);
    const out = [];
    for (let i = 0; i < 6; i++) {
      const gross = base * (1 + i * 0.03);
      const leak = gross * (p.leakagePct || 5) / 100;
      const net = gross - leak;
      const lci = net * (1 - p.uncertaintyPct / 100);
      out.push({ yr: startYr + i, gross, leak, net, lci });
    }
    return out;
  }, [p]);
  const steps = methodSteps(method, p);
  return <div className="vc-in" style={{ display: 'grid', gridTemplateColumns: 'minmax(0,1fr) 380px', gap: 'var(--gap)', height: '100%', minHeight: 0 }}>
    <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--gap)', minHeight: 0 }}>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4,1fr)', gap: 'var(--gap)' }}>
        <Stat label="Gross removals" value={MM(rows[0].gross)} unit="tCO₂e/yr" tone="brand" />
        <Stat label="Leakage deduction" value={'−' + MM(rows[0].leak)} unit="tCO₂e" tone="warn" />
        <Stat label="Net additionality" value={MM(rows[0].net)} unit="tCO₂e/yr" tone="brand" />
        <Stat label="Issuance (lower CI)" value={MM(rows[0].lci)} unit="tCO₂e" tone="teal" sub={`conservative −${p.uncertaintyPct}%`} />
      </div>
      <div className="panel" style={{ flex: 1, minHeight: 0, display: 'flex', flexDirection: 'column' }}>
        <PanelHead icon="pulse" title="Baseline vs. project trajectory" sub="Dynamic baseline · Bayesian CI band"
          right={<Badge tone={curMethod.tone}>{curMethod.short}</Badge>} />
        <div style={{ padding: '14px 16px 4px' }}><BaselineChart project={p} h={210} /></div>
        <div style={{ display: 'flex', gap: 18, padding: '0 16px 14px', fontSize: 11.5 }}>
          <span style={{ display: 'flex', alignItems: 'center', gap: 6, color: 'var(--text-2)' }}><span style={{ width: 14, height: 2, background: 'var(--brand)' }} /> Project scenario</span>
          <span style={{ display: 'flex', alignItems: 'center', gap: 6, color: 'var(--text-2)' }}><span style={{ width: 14, borderTop: '2px dashed var(--text-3)' }} /> Counterfactual baseline</span>
          <span style={{ marginLeft: 'auto', color: 'var(--text-3)' }} className="mono">M tCO₂e · {startYr}–{startYr + p.series.length - 1}</span>
        </div>
      </div>
      <div className="panel">
        <PanelHead icon="calc" title="Credit forecast" sub="Forward projection with confidence bounds" right={<button className="vc-btn-ghost"><Icon name="dl" size={13} /> Export CSV</button>} />
        <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 12.5 }}>
          <thead><tr>{['Vintage', 'Gross', 'Leakage', 'Net', 'Issuance (−CI)', ''].map((h, i) =>
            <th key={i} style={{ textAlign: i === 0 ? 'left' : i === 5 ? 'left' : 'right', padding: '8px 16px', borderBottom: '1px solid var(--line)', color: 'var(--text-3)', fontWeight: 600, fontSize: 10.5, textTransform: 'uppercase', letterSpacing: '.05em' }}>{h}</th>)}</tr></thead>
          <tbody>
            {rows.map((r, i) => <tr key={i} className="vc-row">
              <td className="mono" style={{ padding: '8px 16px', borderBottom: '1px solid var(--line)', color: 'var(--text-1)', fontWeight: 600 }}>{r.yr}</td>
              <td className="mono" style={{ padding: '8px 16px', borderBottom: '1px solid var(--line)', textAlign: 'right', color: 'var(--text-2)' }}>{fmt2(Math.round(r.gross))}</td>
              <td className="mono" style={{ padding: '8px 16px', borderBottom: '1px solid var(--line)', textAlign: 'right', color: 'var(--warn)' }}>−{fmt2(Math.round(r.leak))}</td>
              <td className="mono" style={{ padding: '8px 16px', borderBottom: '1px solid var(--line)', textAlign: 'right', color: 'var(--text-1)' }}>{fmt2(Math.round(r.net))}</td>
              <td className="mono" style={{ padding: '8px 16px', borderBottom: '1px solid var(--line)', textAlign: 'right', color: 'var(--teal)', fontWeight: 600 }}>{fmt2(Math.round(r.lci))}</td>
              <td style={{ padding: '8px 16px', borderBottom: '1px solid var(--line)', width: 90 }}><Bar pct={r.lci / rows[5].gross * 100} tone="teal" /></td>
            </tr>)}
          </tbody>
        </table>
      </div>
    </div>

    {/* right rail: codified methodology logic */}
    <div className="panel" style={{ display: 'flex', flexDirection: 'column', minHeight: 0 }}>
      <PanelHead icon="list" title={curMethod.short + ' computation'} sub={curMethod.name}
        right={<MethodPicker value={method} onChange={setMethod} />} />
      {p.methodology !== method && p.methodology !== method.replace('-', ' ') && <div style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '9px 14px', background: 'color-mix(in srgb, var(--gold) 12%, transparent)', borderBottom: '1px solid var(--line)' }}>
        <Icon name="alert" size={13} c="var(--gold)" />
        <span style={{ fontSize: 11, color: 'var(--text-2)' }}>Previewing <b style={{ color: 'var(--text-1)' }}>{curMethod.short}</b> logic · this project runs <b style={{ color: 'var(--text-1)' }}>{p.methodology}</b>.</span>
      </div>}
      <div style={{ overflow: 'auto', padding: '6px 0' }}>
        {steps.map((s, i) => <div key={i} style={{ display: 'flex', gap: 12, padding: '13px 16px', borderBottom: i < steps.length - 1 ? '1px solid var(--line)' : 'none' }}>
          <div style={{ width: 24, height: 24, flexShrink: 0, borderRadius: 7, background: 'var(--brand-deep)', color: 'var(--brand)', display: 'grid', placeItems: 'center', fontSize: 12, fontWeight: 700, border: '1px solid color-mix(in srgb,var(--brand) 30%,transparent)' }} className="mono">{s.n}</div>
          <div style={{ minWidth: 0 }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
              <span style={{ fontSize: 13, fontWeight: 600, whiteSpace: 'nowrap' }}>{s.t}</span>
            </div>
            <div style={{ fontSize: 11.5, color: 'var(--text-3)', margin: '3px 0 6px', lineHeight: 1.5 }}>{s.d}</div>
            <span className="mono" style={{ fontSize: 11.5, color: 'var(--brand)' }}>{s.v}</span>
          </div>
        </div>)}
        <div style={{ padding: 14 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '10px 12px', borderRadius: 8, background: 'var(--bg-2)', border: '1px solid var(--line)' }}>
            <Icon name="check" size={15} c="var(--brand)" />
            <span style={{ fontSize: 11.5, color: 'var(--text-2)' }}>All parameters logged with audit trail for VVB review.</span>
          </div>
        </div>
      </div>
    </div>
  </div>;
}

/* ===================== COMPLIANCE ENGINE ===================== */
function statusTone(s) { return { pass: 'brand', warn: 'warn', progress: 'info', fail: 'danger' }[s] || 'neutral'; }
function ComplianceView({ project, t }) {
  const p = project;
  const risks = [
    { label: 'Permanence', pct: 84, val: 'Low', tone: 'brand' },
    { label: 'Reversal', pct: 38, val: 'Med', tone: 'warn' },
    { label: 'Leakage', pct: 90, val: 'Low', tone: 'brand' },
    { label: 'Fire', pct: 52, val: 'Watch', tone: 'warn' },
  ];
  return <div className="vc-in" style={{ display: 'grid', gridTemplateColumns: 'minmax(0,1fr) 380px', gap: 'var(--gap)', height: '100%', minHeight: 0 }}>
    <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--gap)', minHeight: 0 }}>
      {/* modules grid */}
      <div className="panel">
        <PanelHead icon="shield" title="Compliance modules" sub="Evidence assembly across VM0048 requirements" right={<Badge tone="info">{p.dossier}% dossier ready</Badge>} />
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4,1fr)', gap: 1, background: 'var(--line)' }}>
          {D2.complianceModules.map((m, i) => <div key={i} style={{ background: 'var(--bg-1)', padding: 14, display: 'flex', flexDirection: 'column', gap: 8, minHeight: 96 }}>
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
              <Icon name={m.icon} size={16} c={`var(--${statusTone(m.status)})`} />
              <Dot s={m.status === 'pass' ? 'ok' : m.status} />
            </div>
            <div style={{ fontSize: 12.5, fontWeight: 600, lineHeight: 1.3 }}>{m.label}</div>
            <div style={{ fontSize: 11, color: 'var(--text-3)', lineHeight: 1.45, marginTop: 'auto' }}>{m.note}</div>
          </div>)}
        </div>
      </div>
      {/* sign-off queue */}
      <div className="panel" style={{ flex: 1, minHeight: 0, display: 'flex', flexDirection: 'column' }}>
        <PanelHead icon="bell" title="Human sign-off queue" sub="AI-flagged gaps awaiting reviewer clearance" right={<Badge tone="warn">{D2.signoffQueue.length} open</Badge>} />
        <div style={{ overflow: 'auto', minHeight: 0 }}>
          {D2.signoffQueue.map((q, i) => <div key={q.id} className="vc-row" style={{ display: 'flex', gap: 12, padding: '12px 16px', borderBottom: '1px solid var(--line)', alignItems: 'center' }}>
            <span style={{ width: 6, height: 36, borderRadius: 4, background: q.sev === 'high' ? 'var(--danger)' : q.sev === 'med' ? 'var(--warn)' : 'var(--text-3)', flexShrink: 0 }} />
            <div style={{ flex: 1, minWidth: 0 }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 3 }}>
                <span className="mono" style={{ fontSize: 11, color: 'var(--text-3)' }}>{q.id}</span>
                <Badge tone={statusTone(q.sev === 'high' ? 'warn' : 'progress')}>{q.type}</Badge>
                <span className="mono" style={{ fontSize: 10.5, color: 'var(--text-3)' }}>{q.clause}</span>
              </div>
              <div style={{ fontSize: 12.5, color: 'var(--text-1)', lineHeight: 1.4 }}>{q.text}</div>
              <div style={{ fontSize: 11, color: 'var(--text-3)', marginTop: 3 }}>{q.project} · flagged by {q.who} · {q.age} ago</div>
            </div>
            <div style={{ display: 'flex', gap: 6, flexShrink: 0 }}>
              <button className="vc-btn-ghost">Review</button>
              <button className="vc-btn">Sign off</button>
            </div>
          </div>)}
        </div>
      </div>
    </div>

    {/* right rail */}
    <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--gap)', minHeight: 0, overflow: 'auto' }}>
      <div className="panel" style={{ padding: 15 }}>
        <span className="lbl">Risk dashboard</span>
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 14, marginTop: 14 }}>
          {risks.map((r, i) => <div key={i} style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 4 }}>
            <Gauge pct={r.pct} value={r.val} tone={r.tone} size={84} sub="" />
            <span className="lbl">{r.label}</span>
          </div>)}
        </div>
      </div>
      <div className="panel">
        <PanelHead icon="spark" title="AI PDD Generator" sub="LLM auto-population" />
        <div style={{ padding: 15 }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 8, fontSize: 12 }}><span style={{ color: 'var(--text-2)' }}>Sections populated</span><span className="mono" style={{ color: 'var(--ai)' }}>12 / 18</span></div>
          <Bar pct={66} tone="ai" />
          <div style={{ fontSize: 11, color: 'var(--text-3)', margin: '10px 0 12px', lineHeight: 1.5 }}>Platform-computed baseline, additionality & leakage piped to the AI PDD Generator. Prep cut from months to days.</div>
          <button className="vc-btn" style={{ width: '100%', justifyContent: 'center' }}><Icon name="ext" size={13} /> Open PDD draft</button>
        </div>
      </div>
      <div className="panel">
        <PanelHead icon="folder" title="Verification dossier" sub="VVB-ready submission package" />
        <div style={{ padding: 15 }}>
          {[['Monitoring report', 100], ['Satellite analysis', 100], ['Field survey records', 92], ['FPIC documentation', 100], ['Additionality evidence', 74], ['Methodology compliance', 62]].map(([k, v], i) =>
            <div key={i} style={{ marginBottom: 11 }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 11.5, marginBottom: 4 }}><span style={{ color: 'var(--text-2)', whiteSpace: 'nowrap' }}>{k}</span><span className="mono" style={{ color: v === 100 ? 'var(--brand)' : 'var(--text-3)' }}>{v}%</span></div>
              <Bar pct={v} tone={v === 100 ? 'brand' : 'info'} h={5} />
            </div>)}
          <button className="vc-btn" style={{ width: '100%', justifyContent: 'center', marginTop: 6 }}><Icon name="dl" size={13} /> Export dossier</button>
        </div>
      </div>
    </div>
  </div>;
}

/* ===================== DATA PIPELINE ===================== */
function PipelineView({ project, t }) {
  const pl = D2.pipeline;
  return <div className="vc-in" style={{ display: 'flex', flexDirection: 'column', gap: 'var(--gap)', height: '100%', minHeight: 0 }}>
    {/* flow */}
    <div className="panel">
      <PanelHead icon="merge" title="End-to-end data flow" sub={`Last run ${pl.lastRun} · next ${pl.nextRun}`} right={<button className="vc-btn-ghost"><Icon name="gear" size={13} /> Configure</button>} />
      <div style={{ display: 'flex', alignItems: 'stretch', gap: 0, padding: 16, overflowX: 'auto' }}>
        {pl.stages.map((s, i) => <React.Fragment key={s.key}>
          <div style={{ flex: 1, minWidth: 130, background: 'var(--bg-2)', border: '1px solid var(--line)', borderRadius: 9, padding: 13, display: 'flex', flexDirection: 'column', gap: 8, position: 'relative' }}>
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
              <Icon name={s.icon} size={16} c={`var(--${STATUS[s.status] ? statusTone2(s.status) : 'text-3'})`} />
              <Dot s={s.status} pulse={s.status === 'running'} />
            </div>
            <div style={{ fontSize: 13, fontWeight: 600 }}>{s.label}</div>
            <div style={{ fontSize: 11, color: 'var(--text-3)', lineHeight: 1.4 }}>{s.detail}</div>
            <span className="mono" style={{ fontSize: 10.5, color: 'var(--text-2)', marginTop: 'auto' }}>{s.ms}</span>
          </div>
          {i < pl.stages.length - 1 && <div style={{ display: 'flex', alignItems: 'center', padding: '0 4px', color: 'var(--text-3)' }}><Icon name="chevR" size={16} /></div>}
        </React.Fragment>)}
      </div>
    </div>

    <div style={{ display: 'grid', gridTemplateColumns: 'minmax(0,1fr) 360px', gap: 'var(--gap)', flex: 1, minHeight: 0 }}>
      {/* source catalog */}
      <div className="panel" style={{ display: 'flex', flexDirection: 'column', minHeight: 0 }}>
        <PanelHead icon="sat" title="Dataset register" sub={`${pl.sources.length} sources · GEE + non-GEE APIs`} right={<><Badge tone="brand">{pl.sources.filter(s => s.status === 'live').length} live</Badge><Badge tone="ai">{pl.sources.filter(s => s.nonGee).length} non-GEE</Badge></>} />
        <div style={{ overflow: 'auto', minHeight: 0 }}>
          <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 12 }}>
            <thead><tr style={{ position: 'sticky', top: 0, background: 'var(--bg-1)' }}>{['', 'Dataset', 'Provider', 'Res.', 'Cadence', 'Cost', 'Latency'].map((h, i) =>
              <th key={i} style={{ textAlign: i > 2 && i < 6 ? 'center' : 'left', padding: '9px 14px', borderBottom: '1px solid var(--line)', color: 'var(--text-3)', fontWeight: 600, fontSize: 10, textTransform: 'uppercase', letterSpacing: '.05em' }}>{h}</th>)}</tr></thead>
            <tbody>
              {pl.sources.map((s, i) => <tr key={i} className="vc-row">
                <td style={{ padding: '9px 14px', borderBottom: '1px solid var(--line)', width: 20 }}><Dot s={s.status} pulse={s.status === 'live' && i < 2} /></td>
                <td style={{ padding: '9px 14px', borderBottom: '1px solid var(--line)', color: 'var(--text-1)', fontWeight: 500 }}>
                  <span style={{ display: 'inline-flex', alignItems: 'center', gap: 7 }}>{s.name}{s.nonGee && <span style={{ fontSize: 9, fontWeight: 700, letterSpacing: '.04em', padding: '1px 5px', borderRadius: 4, color: 'var(--ai)', background: 'color-mix(in srgb,var(--ai) 14%,transparent)', border: '1px solid color-mix(in srgb,var(--ai) 28%,transparent)' }}>API</span>}</span>
                </td>
                <td style={{ padding: '9px 14px', borderBottom: '1px solid var(--line)', color: 'var(--text-3)' }}>{s.provider}</td>
                <td className="mono" style={{ padding: '9px 14px', borderBottom: '1px solid var(--line)', textAlign: 'center', color: 'var(--text-2)' }}>{s.res}</td>
                <td className="mono" style={{ padding: '9px 14px', borderBottom: '1px solid var(--line)', textAlign: 'center', color: 'var(--text-2)' }}>{s.cadence}</td>
                <td style={{ padding: '9px 14px', borderBottom: '1px solid var(--line)', textAlign: 'center' }}><Badge tone={s.cost === 'Free' ? 'brand' : s.cost === 'Fallback' ? 'neutral' : 'gold'}>{s.cost}</Badge></td>
                <td className="mono" style={{ padding: '9px 14px', borderBottom: '1px solid var(--line)', textAlign: 'right', color: 'var(--text-3)' }}>{s.latency}</td>
              </tr>)}
            </tbody>
          </table>
        </div>
      </div>
      {/* right: router + cost */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--gap)', minHeight: 0, overflow: 'auto' }}>
        <div className="panel">
          <PanelHead icon="merge" title="AGBD inference router" sub="Single env-var switch" />
          <div style={{ padding: 14, display: 'flex', flexDirection: 'column', gap: 8 }}>
            {[['Active', pl.router.active, 'brand', true], ['Fallback', pl.router.fallback, 'teal', false], ['Internal ML', pl.router.internal, 'neutral', false]].map(([k, v, tone, on], i) =>
              <div key={i} style={{ display: 'flex', alignItems: 'center', gap: 10, padding: '10px 12px', borderRadius: 8, background: 'var(--bg-2)', border: `1px solid ${on ? 'color-mix(in srgb,var(--brand) 35%,transparent)' : 'var(--line)'}` }}>
                <Dot s={on ? 'ok' : 'idle'} pulse={on} />
                <div style={{ flex: 1, minWidth: 0 }}><div className="lbl">{k}</div><div className="mono" style={{ fontSize: 11.5, color: 'var(--text-2)', marginTop: 2 }}>{v}</div></div>
                {on && <Badge tone="brand" solid>routing</Badge>}
              </div>)}
          </div>
        </div>
        <div className="panel">
          <PanelHead icon="cpu" title="GEE & compute" sub="Phase 1 · manual trigger" />
          <div style={{ padding: 14 }}>
            <HBars items={[{ label: 'Tiles processed', v: 1240000, c: 'var(--brand)' }, { label: 'EECU-hours', v: 86, c: 'var(--teal)' }, { label: 'GCS storage GB', v: 412, c: 'var(--gold)' }, { label: 'Cloud Run reqs', v: 318, c: 'var(--info)' }]} fmtv={(v) => v >= 1e6 ? (v / 1e6).toFixed(1) + 'M' : fmt2(v)} />
            <hr className="hair" style={{ margin: '14px 0' }} />
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline' }}>
              <span style={{ fontSize: 12, color: 'var(--text-2)' }}>Est. monthly infra</span>
              <span className="kpi-num" style={{ fontSize: 18, color: 'var(--text-1)' }}>$320<span style={{ fontSize: 11, color: 'var(--text-3)' }}>/mo</span></span>
            </div>
            <div style={{ fontSize: 10.5, color: 'var(--text-3)', marginTop: 4 }}>GEE free tier · Google for Startups credits applied</div>
          </div>
        </div>
      </div>
    </div>
  </div>;
}
function statusTone2(s) { return { ok: 'brand', live: 'brand', running: 'teal', queued: 'gold', idle: 'text-3', standby: 'text-3' }[s] || 'text-3'; }

/* ===================== FIELD COMPANION ===================== */
function FieldView({ project, t }) {
  const subs = D2.fieldSubs;
  const synced = subs.filter(s => s.sync === 'synced').length;
  return <div className="vc-in" style={{ display: 'grid', gridTemplateColumns: '300px minmax(0,1fr)', gap: 'var(--gap)', height: '100%', minHeight: 0 }}>
    {/* phone */}
    <div className="panel" style={{ display: 'flex', flexDirection: 'column', minHeight: 0 }}>
      <PanelHead icon="phone" title="Field app" sub="Offline-first · KoboCollect" />
      <div style={{ flex: 1, display: 'grid', placeItems: 'center', padding: 16, overflow: 'auto', background: 'var(--bg-0)' }}>
        <Phone project={project} />
      </div>
    </div>

    {/* right: submissions + enumerators */}
    <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--gap)', minHeight: 0 }}>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4,1fr)', gap: 'var(--gap)' }}>
        <Stat label="Submissions today" value="18" tone="brand" />
        <Stat label="Sync queue" value={subs.length - synced} unit="pending" tone="warn" />
        <Stat label="Active enumerators" value="6" sub="3 sites" />
        <Stat label="Trees measured" value="2,140" unit="DBH+H" tone="teal" />
      </div>
      <div className="panel" style={{ flex: 1, minHeight: 0, display: 'flex', flexDirection: 'column' }}>
        <PanelHead icon="upload" title="Recent field submissions" sub="Synced from offline devices" right={<Badge tone={subs.length - synced ? 'warn' : 'brand'}>{synced}/{subs.length} synced</Badge>} />
        <div style={{ overflow: 'auto', minHeight: 0 }}>
          <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 12.5 }}>
            <thead><tr style={{ position: 'sticky', top: 0, background: 'var(--bg-1)' }}>{['', 'ID', 'Plot', 'Form', 'Enumerator', 'GPS', 'When', 'Sync'].map((h, i) =>
              <th key={i} style={{ textAlign: 'left', padding: '9px 14px', borderBottom: '1px solid var(--line)', color: 'var(--text-3)', fontWeight: 600, fontSize: 10, textTransform: 'uppercase', letterSpacing: '.05em' }}>{h}</th>)}</tr></thead>
            <tbody>
              {subs.map(s => <tr key={s.id} className="vc-row">
                <td style={{ padding: '10px 14px', borderBottom: '1px solid var(--line)', width: 16 }}><Icon name={s.type.includes('DBH') ? 'tree' : s.type.includes('SOC') ? 'layers' : s.type.includes('acoustic') ? 'pulse' : 'doc'} size={14} c="var(--text-3)" /></td>
                <td className="mono" style={{ padding: '10px 14px', borderBottom: '1px solid var(--line)', color: 'var(--text-3)' }}>{s.id}</td>
                <td className="mono" style={{ padding: '10px 14px', borderBottom: '1px solid var(--line)', color: 'var(--text-1)' }}>{s.plot}</td>
                <td style={{ padding: '10px 14px', borderBottom: '1px solid var(--line)', color: 'var(--text-2)' }}>{s.type}{s.trees ? <span className="mono" style={{ color: 'var(--text-3)' }}> · {s.trees}</span> : ''}</td>
                <td style={{ padding: '10px 14px', borderBottom: '1px solid var(--line)', color: 'var(--text-2)' }}>{s.enum}</td>
                <td className="mono" style={{ padding: '10px 14px', borderBottom: '1px solid var(--line)', color: 'var(--text-3)', fontSize: 11 }}>{s.gps}</td>
                <td style={{ padding: '10px 14px', borderBottom: '1px solid var(--line)', color: 'var(--text-3)' }}>{s.when}</td>
                <td style={{ padding: '10px 14px', borderBottom: '1px solid var(--line)' }}>{s.sync === 'synced' ? <Badge tone="brand"><Icon name="check" size={11} /> synced</Badge> : <Badge tone="warn"><Icon name="clock" size={11} /> pending</Badge>}</td>
              </tr>)}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>;
}

function Phone({ project }) {
  return <div style={{ width: 252, height: 512, borderRadius: 30, background: '#05090a', border: '8px solid #1b2420', boxShadow: '0 24px 60px -20px rgba(0,0,0,.8)', padding: 0, position: 'relative', overflow: 'hidden', flexShrink: 0 }}>
    {/* notch */}
    <div style={{ position: 'absolute', top: 8, left: '50%', transform: 'translateX(-50%)', width: 70, height: 5, borderRadius: 9, background: '#1b2420', zIndex: 3 }} />
    {/* status bar */}
    <div style={{ display: 'flex', justifyContent: 'space-between', padding: '10px 16px 6px', fontSize: 10, color: '#cfe', position: 'relative', zIndex: 2 }} className="mono">
      <span>08:42</span><span style={{ display: 'flex', gap: 5, alignItems: 'center' }}><Icon name="alert" size={10} c="#f0a92c" /> offline · 12 queued</span>
    </div>
    <div style={{ background: 'var(--brand-deep)', padding: '12px 16px', display: 'flex', alignItems: 'center', gap: 9 }}>
      <Icon name="tree" size={18} c="var(--brand)" />
      <div><div style={{ fontSize: 12.5, fontWeight: 700, color: '#eafff0' }}>Verst Field</div><div style={{ fontSize: 9.5, color: '#8fbfa0' }} className="mono">{project.code} · Plot TSE-P14</div></div>
    </div>
    <div style={{ padding: 14, display: 'flex', flexDirection: 'column', gap: 11, background: '#0b1410', height: 'calc(100% - 92px)', overflow: 'auto' }}>
      <div style={{ fontSize: 11, fontWeight: 700, color: '#cfe', letterSpacing: '.04em' }}>DBH & HEIGHT SURVEY</div>
      {[['Tree #', '42 of 50'], ['Species', 'Acacia tortilis'], ['DBH (cm)', '24.6'], ['Height (m)', '8.2']].map(([k, v], i) =>
        <div key={i}>
          <div style={{ fontSize: 9.5, color: '#7a9488', marginBottom: 4 }} className="mono">{k}</div>
          <div style={{ background: '#13201a', border: '1px solid rgba(255,255,255,.08)', borderRadius: 8, padding: '9px 11px', fontSize: 12.5, color: '#eafff0', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <span className={i > 1 ? 'mono' : ''}>{v}</span>{i > 1 && <Icon name="plus" size={13} c="var(--brand)" />}
          </div>
        </div>)}
      <div style={{ display: 'flex', gap: 8, alignItems: 'center', padding: '9px 11px', background: '#13201a', border: '1px solid rgba(255,255,255,.08)', borderRadius: 8 }}>
        <Icon name="crosshair" size={14} c="var(--teal)" />
        <span className="mono" style={{ fontSize: 10.5, color: '#9fc' }}>-2.741, 38.793</span>
        <Badge tone="teal">GNSS</Badge>
      </div>
      <button style={{ marginTop: 'auto', border: 'none', borderRadius: 9, padding: '12px', background: 'var(--brand)', color: '#08130d', fontWeight: 700, fontSize: 13, cursor: 'pointer' }}>Save & next tree</button>
    </div>
  </div>;
}

Object.assign(window, { AccountingView, ComplianceView, PipelineView, FieldView });
